b AS (SELECT coalesce(nullif($1, ''), (SELECT nullif(valor, '') FROM compras_config WHERE clave = 'base'),
                (SELECT base FROM ms_ventas WHERE fecha >= current_date - 90 GROUP BY base ORDER BY count(*) DESC LIMIT 1), '') AS base,
             coalesce(nullif($5, '')::date, (now() AT TIME ZONE 'America/Mexico_City')::date) AS hoy,
             $2::jsonb || coalesce((SELECT jsonb_object_agg(clave, valor) FROM compras_config WHERE coalesce(valor, '') <> ''), '{}'::jsonb) AS c,
             $4::jsonb AS p, $3::text AS por),
cfg AS (SELECT b.*,
             greatest(least(coalesce(nullif(c->>'meses_abc', '')::int, 6), 24), 1) AS meses,
             coalesce(nullif(c->>'corte_a', '')::numeric, 80) / 100 AS corte,
             coalesce(nullif(c->>'seg_a', '')::numeric, 3) AS seg_a, coalesce(nullif(c->>'inv_a', '')::numeric, 15) AS inv_a,
             coalesce(nullif(c->>'seg_b', '')::numeric, 5) AS seg_b, coalesce(nullif(c->>'inv_b', '')::numeric, 30) AS inv_b,
             coalesce(nullif(c->>'entrega_def', '')::numeric, 3) AS ent_def,
             coalesce(nullif(c->>'dia_a', '')::int, 1) AS dia_a, coalesce(nullif(c->>'frec_b', '')::int, 15) AS frec_b,
             coalesce(nullif(c->>'regla', ''), 'bajo_minimo') AS regla, coalesce(nullif(c->>'gracia_oc', '')::int, 5) AS gracia,
             coalesce(nullif(c->>'dias_ligar', '')::int, 7) AS dias_ligar,
             coalesce(c->>'almacenes', '') AS alm, coalesce(c->>'excluir', '') AS excl, coalesce(c->>'lineas_excluidas', '') AS excl_lin,
             greatest(least(coalesce(nullif(c->>'meses_c', '')::int, 12), 36), 1) AS meses_c,
             coalesce(nullif(c->>'seg_c', '')::numeric, 5) AS seg_c, coalesce(nullif(c->>'inv_c', '')::numeric, 30) AS inv_c,
             greatest(coalesce(nullif(c->>'min_c', '')::numeric, 1), 1) AS min_c,
             greatest(coalesce(nullif(c->>'max_lento', '')::numeric, 1), 1) AS max_lento,
             coalesce(nullif(c->>'metodo', ''), 'retail') AS metodo,
             coalesce(nullif(c->>'ns_a', '')::numeric, 95) AS ns_a, coalesce(nullif(c->>'ns_b', '')::numeric, 90) AS ns_b,
             coalesce(nullif(c->>'ns_c', '')::numeric, 85) AS ns_c,
             coalesce(nullif(c->>'rev_a', '')::numeric, 7) AS rev_a,
             coalesce(nullif(c->>'rot_alta', '')::numeric, 50) / 100 AS rot_alta, coalesce(nullif(c->>'rot_media', '')::numeric, 20) / 100 AS rot_media,
             coalesce(c->>'palabras_distintas', '') AS palabras_distintas,
             coalesce(nullif(c->>'monto_maximo', '')::numeric, 500000) AS maxm
        FROM b)
